In [25]:
from python_speech_features import mfcc
from python_speech_features import delta
import matplotlib.pyplot as plt
from scipy.io import wavfile as wav
from scipy.fftpack import fft
import numpy as np
import pandas as pd

In [3]:
column1 = ['mf1','mf2','mf3','mf4','mf5','mf6','mf7','mf8','mf9','mf10']
column3 = ['mx1','mx2','mx3','mx4','mx5','mx6','mx7','mx8','mx9','mx10']
column2 = ['delta_1','delta_2','delta_3','delta_4','delta_5','delta_6','delta_7','delta_8','delta_9','delta_10']
column4 = ['mn1','mn2','mn3','mn4','mn5','mn6','mn7','mn8','mn9','mn10']
column5 = ['delta_1_mx','delta_2_mx','delta_3_mx','delta_4_mx','delta_5_mx','delta_6_mx','delta_7_mx','delta_8_mx','delta_9_mx','delta_10_mx']
column6 =  ['delta_1_mn','delta_2_mn','delta_3_mn','delta_4_mn','delta_5_mn','delta_6_mn','delta_7_mn','delta_8_mn','delta_9_mn','delta_10_mn']
#column7 =  ['delta_1_m','delta_2_mx','delta_3_mx','delta_4_mx','delta_5_mx','delta_6_mx','delta_7_mx','delta_8_mx','delta_9_mx','delta_10_mx']

In [4]:
#Data Reading for 1st dialect

total_data_1 = [] # we will append data of ist dialect here from every file to i

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR1/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_1= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_1['outcome'] = [1 for i in range(len(dialect_1))]
    total_data_1.append(dialect_1)
#including energy as also as one feature

In [5]:
total_data_1[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,10.003578,-4.511844,1.595553,1.637113,-5.933956,-5.787712,-5.722199,0.836042,-5.372129,-2.860997,...,-50.90541,-45.514845,-40.868705,-60.692558,-52.516331,-53.582011,-46.788736,-47.520776,-38.263635,1

In [6]:
#Data Reading for 2nd dialect

total_data_2 = [] # we will append data of ist dialect here from every file to i


for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR2/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_2= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_2['outcome'] = [2 for i in range(len(dialect_2))]
    total_data_2.append(dialect_2)
    
#including energy as also as one feature

In [7]:
total_data_2[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,15.681064,2.016116,6.838558,2.479362,5.807435,-7.09143,-9.607075,-9.716152,-5.873127,-4.451606,...,-50.410003,-27.068013,-36.288916,-31.389175,-53.715406,-53.8797,-46.13167,-55.602865,-48.510902,2

In [8]:
#Data Reading for 3rd dialect

total_data_3 = [] # we will append data of ist dialect here from every file to i

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR3/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_3= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_3['outcome'] = [3 for i in range(len(dialect_3))]
    total_data_3.append(dialect_3)

In [9]:
total_data_3[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,15.77709,-2.234128,1.596057,3.257132,-7.676189,0.880079,-23.655341,-3.211201,1.631082,-8.143383,...,-49.495785,-38.053379,-46.026205,-69.428626,-42.089652,-75.609935,-48.285575,-47.651723,-42.760694,3

In [10]:
#Data Reading for 4rt dialect

total_data_4 = [] # we will append data of ist dialect here from every file to i

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR4/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_4= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_4['outcome'] = [4 for i in range(len(dialect_4))]
    total_data_4.append(dialect_4)

In [11]:
total_data_4[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,13.351718,-6.001978,-6.740877,7.97803,-12.016157,-6.801061,-3.869301,-5.7804,-4.806032,-2.267165,...,-52.800949,-48.072672,-33.565037,-69.76253,-61.412766,-47.547147,-60.73951,-59.673472,-64.169689,4

In [12]:
#Data Reading for 5th dialect

total_data_5 = [] # we will append data of ist dialect here from every file to i

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR5/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_5 = pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_5['outcome'] = [5 for i in range(len(dialect_5))]
    total_data_5.append(dialect_5)

In [13]:
total_data_5[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,15.338123,-1.609346,-1.80217,-0.530143,-8.39932,-12.986251,-15.055067,-7.842124,0.608864,4.354152,...,-50.775941,-39.413472,-37.585384,-52.418541,-70.199119,-66.793599,-52.452605,-40.076095,-33.205373,5

In [14]:
#Data Reading for 6th dialect

total_data_6 = [] # we will append data of ist dialect here from every file to i

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR6/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_6= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_6['outcome'] = [6 for i in range(len(dialect_6))]
    total_data_6.append(dialect_6)

In [15]:
total_data_6[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,13.834051,-4.367052,-6.395434,3.851064,-6.96355,-2.024361,-4.569719,-5.167255,-2.426174,-1.456726,...,-57.327973,-51.491652,-35.152879,-67.160476,-54.9068,-52.027775,-52.92574,-67.050018,-51.343814,6

In [16]:
#Data Reading for 7th dialect

total_data_7 = [] # we will append data of ist dialect here from every file to i

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR7/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_7= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_7['outcome'] = [7 for i in range(len(dialect_7))]
    total_data_7.append(dialect_7)

In [17]:
total_data_7[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,16.670178,-6.05327,0.006048,0.452055,-15.388886,-8.874267,-16.238572,-3.606411,-6.393011,1.220219,...,-47.375845,-50.95281,-43.097476,-68.542629,-51.985072,-60.783425,-44.762977,-43.437153,-46.070545,7

In [18]:
total_data_8 = []

for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR8/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_8= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_8['outcome'] = [8 for i in range(len(dialect_8))]
    total_data_8.append(dialect_8)

In [19]:
total_data_8[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,16.137695,-0.068664,6.245778,8.559584,-10.09805,-5.773552,-15.539576,-11.724794,-8.725598,-10.259638,...,-51.553635,-39.620251,-41.682088,-56.867318,-55.960606,-56.260142,-59.605652,-54.697982,-54.944086,8

In [20]:
total_data_9 = [] # we will append data of ist dialect here from every file to i
for i in range(1,68):
    [fs,data] = wav.read("Read_Up/IDR9/{}.wav".format(i))    
    #extracting mfcc features 
    mfcc_data = mfcc(data,fs,numcep = 10)
    
    mfcc_data_max = np.max(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_min = np.min(mfcc_data,axis = 0)[np.newaxis]
    mfcc_data_mean = np.mean(mfcc_data,axis = 0)[np.newaxis]
    
    mfcc_data_mean = pd.DataFrame(data = mfcc_data_mean,columns = column1)
    mfcc_data_max = pd.DataFrame(data = mfcc_data_max,columns = column3)
    mfcc_data_min = pd.DataFrame(data = mfcc_data_min,columns = column4)
    #extracting delta_feat 
    
    delta_feat = delta(mfcc_data,4)
    delta_feat_mean = np.mean(delta_feat,axis = 0)[np.newaxis]
    delta_feat_max =  np.max(mfcc_data,axis = 0)[np.newaxis]
    delta_feat_min =  np.min(mfcc_data,axis = 0)[np.newaxis]
    
    delta_feat_mean = pd.DataFrame(data = delta_feat_mean,columns = column2)
    delta_feat_max = pd.DataFrame(data = delta_feat_max,columns = column5)
    delta_feat_min = pd.DataFrame(data = delta_feat_min,columns = column6)
    
    #concating all the features 
    dialect_9= pd.concat([mfcc_data_mean,mfcc_data_min,mfcc_data_max,delta_feat_mean,delta_feat_max,delta_feat_min],axis = 1)
    dialect_9['outcome'] = [9 for i in range(len(dialect_7))]
    total_data_9.append(dialect_9)

In [21]:
total_data_9[1]

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,13.794045,4.396554,-4.540314,14.452914,-4.80475,-1.570537,-4.426809,1.669677,2.677332,3.184568,...,-50.054104,-50.088279,-34.128823,-68.112238,-45.63293,-57.784814,-38.519227,-50.79034,-44.795046,9

In [22]:
#concating all the data into the single list
total_dt = []
total_dt.extend(total_data_1)
total_dt.extend(total_data_2)
total_dt.extend(total_data_3)
total_dt.extend(total_data_4)
total_dt.extend(total_data_5)
total_dt.extend(total_data_6)
total_dt.extend(total_data_7)
total_dt.extend(total_data_8)
total_dt.extend(total_data_9)
data = pd.concat(total_dt)
data = data.reset_index().drop(columns = ['index'])
data

,mf1,mf2,mf3,mf4,mf5,mf6,mf7,mf8,mf9,mf10,...,delta_2_mn,delta_3_mn,delta_4_mn,delta_5_mn,delta_6_mn,delta_7_mn,delta_8_mn,delta_9_mn,delta_10_mn,outcome
0,11.097344,-3.326584,0.680139,0.055663,-10.214611,-1.785550,-8.312622,3.104357,-6.690428,1.888162,...,-50.465082,-45.545607,-44.326784,-67.125512,-42.360798,-64.001642,-36.635149,-51.582906,-34.811443,1
1,10.003578,-4.511844,1.595553,1.637113,-5.933956,-5.787712,-5.722199,0.836042,-5.372129,-2.860997,...,-50.905410,-45.514845,-40.868705,-60.692558,-52.516331,-53.582011,-46.788736,-47.520776,-38.263635,1
2,13.318967,-4.653587,-0.005895,5.924639,1.058780,-5.668051,4.494137,1.143804,5.280090,6.372887,...,-54.056983,-39.362237,-35.232346,-62.603300,-68.363041,-42.453761,-50.444713,-35.501828,-29.450849,1
3,14.452624,3.281742,-1.101412,7.817345,-0.173810,-8.532174,4.125723,-6.955924,-2.612741,7.726896,...,-52.294686,-40.822669,-31.050801,-60.855913,-70.206775,-35.210336,-57.558525,-58.409567,-29.552644,1
4,10.639425,-3.107951,-0.413754,-0.345316,-10.380582,-1.631719,-6.303165,-0.536039,-5.869256,-5.213961,...,-52.789653,-46.714735,-49.615961,-66.271962,-57.103406,-57.080820,-40.124654,-42.393622,-51.979374,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,14.860461,-1.110624,-0.069104,4.281378,-12.855471,-6.655679,-8.082432,-6.617781,7.670221,-8.723912,...,-51.384732,-41.131891,-30.433086,-62.965537,-53.349665,-50.930324,-50.665444,-37.009912,-48.304468,9
599,14.681898,-2.387841,0.652945,2.907333,-7.405527,-9.045944,-16.245619,-3.553760,1.470193,-3.279403,...,-55.649833,-32.429687,-30.617856,-58.215065,-52.341376,-58.884712,-46.740123,-33.698643,-36.999646,9
600,14.646025,-10.693862,0.500300,8.865209,-6.294354,-6.449905,-6.152238,-10.093816,-5.344954,-3.495880,...,-52.814427,-34.666475,-25.634814,-52.822000,-54.777019,-48.482026,-60.158207,-41.918471,-45.839833,9
601,12.926165,1.691783,-3.205553,15.508903,-1.533833,0.983289,-2.683774,2.748304,1.808002,3.106002,...,-47.603753,-39.643627,-20.406952,-58.241411,-47.094169,-49.385090,-37.546603,-35.192541,-49.396052,9
602,13.088882,-3.354690,-2.291748,8.920913,-1.563184,-2.688867,-7.854639,-10.451918,-0.506838,-5.262583,...,-49.157915,-30.225209,-31.061881,-50.994550,-52.766565,-49.980973,-64.433048,-42.774994,-37.856318,9

In [34]:
data_train, data_test = train_test_split(data, test_size=0.3)
x_train = data_train.drop(data_train[['outcome']],axis=1)
y_train = data_train[['outcome']]

x_test = data_test.drop(data_test[['outcome']],axis=1)
y_test = data_test[['outcome']]

In [38]:
features = ['mf1','mf2','mf3','mf4','mf5','mf6','mf7','mf8','mf9','mf10','mx1','mx2','mx3','mx4','mx5','mx6','mx7','mx8','mx9','mx10','mn1','mn2','mn3','mn4','mn5','mn6','mn7','mn8','mn9','mn10']
# #features'mf1','mf2','mf3','mf4','mf5','mf6','mf7','mf8','mf9','mf10','mx1','mx2','mx3','mx4','mx5','mx6','mx7','mx8','mx9','mx10','delta_1','delta_2','delta_3','delta_4','delta_5','delta_6','delta_7','delta_8','delta_9','delta_10','mn1','mn2','mn3','mn4','mn5','mn6','mn7','mn8','mn9','mn10']
# #features = ['mfcc','delta']
# outcome = ['outcome']
# X = data[features] #represents feature values
# Y = data[outcome] #represents outcome values 

# #Splitting the data into test and train sets

x_train = x_train[features]
x_test = x_test[features]
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler

# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30, shuffle='True')
from sklearn.svm import SVC
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

clf = SVC(gamma='auto')
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)
clf.score(x_test, y_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  # Remove the CWD from sys.path while we load stuff.

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
#creating model
from sklearn.svm import SVC

from sklearn import metrics
#using the classifier

svclassifier = SVC(gamma = 'auto',kernel = 'linear')
svclassifier.fit(X_train, Y_train)
predict_data = svclassifier.predict(X_test)
print("Accuracy = {0:.3f}".format(metrics.accuracy_score(Y_test, predict_data)))

In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(X_train,Y_train)
logmodel.score(X_test, Y_test)